
name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  API_IMAGE: regression-api
  FRONTEND_IMAGE: regression-frontend

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pip install flake8
          flake8 .

      - name: Test
        run: |
          pytest -q

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push API Image
        run: |
          docker build -f Dockerfile.api -t $REGISTRY/${{ env.API_IMAGE }}:${{ github.sha }} .
          docker push $REGISTRY/${{ env.API_IMAGE }}:${{ github.sha }}

      - name: Build & Push Frontend Image
        run: |
          docker build -f Dockerfile.frontend -t $REGISTRY/${{ env.FRONTEND_IMAGE }}:${{ github.sha }} .
          docker push $REGISTRY/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      - name: Update Azure WebApp (API)
        run: |
          az webapp config container set             --resource-group ${{ secrets.RESOURCE_GROUP }}             --name ${{ secrets.API_APP_NAME }}             --container-image-name $REGISTRY/${{ env.API_IMAGE }}:${{ github.sha }}
          az webapp restart             --resource-group ${{ secrets.RESOURCE_GROUP }}             --name ${{ secrets.API_APP_NAME }}

      - name: Update Azure WebApp (Frontend)
        run: |
          az webapp config appsettings set             --resource-group ${{ secrets.RESOURCE_GROUP }}             --name ${{ secrets.FRONTEND_APP_NAME }}             --settings API_URL=https://${{ secrets.API_APP_NAME }}.azurewebsites.net
          az webapp config container set             --resource-group ${{ secrets.RESOURCE_GROUP }}             --name ${{ secrets.FRONTEND_APP_NAME }}             --container-image-name $REGISTRY/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          az webapp restart             --resource-group ${{ secrets.RESOURCE_GROUP }}             --name ${{ secrets.FRONTEND_APP_NAME }}
